### ISSUE TITLE
node_modules should not be pushed

### ISSUE THREAD

**Issue by UtopiaBeam** [2110423-2019-2/sec3_catandfriends#1]
I saw `node_modules` folders were pushed in both frontend and backend. I think it is because of incorrect paths in `.gitignore`. It should be `node_modules` instead of `/node_modules` (remove `/`).

**Comment by saint1998** [comment]
if I edit .gitignore will the folder disappear or I have to delete it myself.

**Comment by UtopiaBeam** [comment]
> if I edit .gitignore will the folder disappear or I have to delete it myself.

You must delete it first, then edit `.gitignore`.

**Comment by NatthanonM** [comment]
thank you
